---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: gen-policy-generator-observe
policyDefaults:
  namespace: acm-install-policies
  remediationAction: enforce
  consolidateManifests: false
  policySets:
    - acm-observability
placementBindingDefaults:
  name: "acm-observe-binding"

policies:
  - name: acm-observe
    remediationAction: enforce
    manifests:
      - path: config/namespace.yml
      - path: config/console.yml
      - path: config/pull-secret.yml
      - path: config/objectbucketclaim.yml
        extraDependencies: 
          - name: odf-operator-status
            kind: Policy
            compliance: "Compliant"
      - path: config/noobaa-cert-secret.yml
        extraDependencies: 
          - name: odf-operator-status
            kind: Policy
            compliance: "Compliant"      
      - path: config/thanos-secret.yml
        extraDependencies: 
          - name: acm-observe5
            kind: ConfigurationPolicy
            compliance: "Compliant"
      - path: config/observability.yml
        extraDependencies: 
          - name: thanos-secret
            kind: ConfigurationPolicy
            compliance: "Compliant"

  - name: acm-observe-status
    remediationAction: inform
    dependencies:
      - name: "acm-observe"
        compliance: "Compliant"
    manifests:
      - path: health/acm-observability-status.yml

policySets:
  - name: acm-observability
    placement:
      placementRulePath: placements/hub-placement.yaml
#    placement:
#      placementName: "ft-acm-observability--enabled"

