apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: splunk-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: cluster-logging-operator