apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-logging-operator
  namespace: openshift-logging
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::173994873460:role/ocp-access-to-aws-secrets # $ESO_ROLE_ARN