---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: gen-policy-generator-quay
policyDefaults:
  namespace: acm-install-policies
  remediationAction: enforce
  consolidateManifests: false
  policySets:
    - quay-hub
placementBindingDefaults:
  name: "quay-binding"

policies:
  # Quay Policies - start
  - name: policy-install-quay
    manifests:
      - path: config/policy-install-quay.yaml
  - name: policy-config-quay
    dependencies:
      - name: policy-install-quay
    manifests:
      - path: config/policy-config-quay.yaml
  - name: policy-quay-status
    dependencies:
      - name: policy-install-quay
    manifests:
      - path: config/policy-quay-status.yaml
    remediationAction: inform
  - name: external-secret-quay
    manifests:
      - path: config/policy-quay-externalsecret.yaml
      - path: config/policy-quay-secretstore.yaml    
  # - name: quay QuayEcosystem
  #   manifests:
  #     - path: config/policy-quayecosystem.yaml  
  # Quay Bridge is configured with a temporary token that will expire quickly after
  # deployment.  After quay is running, see the instructions:
  # https://hybrid-cloud-patterns.io/devsecops/getting-started/#completing-the-quay-bridge-with-a-bearer-token
  # Update the token in the quayadmin secret in the local-quay namespace with your
  # bearer token.  It will be propagated to the managed clusters automatically.
  - name: policy-hub-quay-bridge
    dependencies:
      - name: policy-quay-status
    manifests:
      - path: config/policy-hub-quay-bridge.yaml
  - name: policy-install-cso
    dependencies:
      - name: policy-quay-status
    manifests:
      - path: config/policy-install-cso.yaml
  - name: policy-cso-status
    dependencies:
      - name: policy-install-cso
    manifests:
      - path: config/policy-cso-status.yaml
    remediationAction: inform
  - name: policy-quay-bridge
    manifests:
      - path: config/policy-quay-bridge.yaml
    orderManifests: true
    policySets:
      - quay-clusters
  # Quay Policies - end
policySets:
  - name: quay-hub
    placement:
      placementRulePath: placements/hub-placement.yaml

  - name: quay-clusters
    placement:
      placementRulePath: placements/clusters-placement.yaml