apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: operator.external-secrets.io/v1alpha1
kind: OperatorConfig
metadata:
  name: cluster
spec:
  prometheus:
    enabled: true
    service:
      port: 8080
  resources:
    requests:
      cpu: 10m
      memory: 96Mi
    limits:
      cpu: 100m  