---
- name: create trident namespace
  k8s:
    host: "https://api.{{ cluster_address }}:6443"
    validate_certs: no
    state: "{{ state }}"
    definition:
    kind: Project
    apiVersion: project.openshift.io/v1
    metadata:
    name: trident


- name: Download the trident installer & run the helm chart in trident directory
  file: 
    name: trident
    state: directory 
  get_url:
    url: https://github.com/NetApp/trident/releases/download/v22.10.0/trident-installer-22.10.0.tar.gz
    dest: trident
  unarchive: 
    src: trident-installer-24.02.0.tar.gz
    dest: trident 

- hosts: localhost
  tasks:
     - name: Install Trident Helm Chart
       kubernetes.core.helm_plugin:
           name: trident
           chart: trident
           values_file: trident/trident-installer/helm/trident-operator-22.10.0.tgz
           namespace: trident
           chart_ref: trident

- name: create secret to store the SVM username & password on the ROSA cluster
  k8s:
    host: "https://api.{{ cluster_address }}:6443"
    validate_certs: no
    state: "{{ state }}"
    definition:
      kind: Secret
      apiVersion: v1
      metadata:
        name: 
        namespace: trident
      data:
        password: vsadmin
        username: NmeOMJFFNHjgIcrA2dqo  

- name: Configure Trident CSI backend to FSx for ONTAP 
  k8s:
    host: "https://api.{{ cluster_address }}:6443"
    validate_certs: no
    state: "{{ state }}"
    definition: 
    apiVersion: v1
    kind: Secret
    metadata:
      name: tbc-ontap-nas-01-secret
    type: Opaque
    stringData:
      username: xxxxxxxxx
      password: xxxxxxxxx
    
      apiVersion: trident.netapp.io/v1
      kind: TridentBackendConfig
      metadata:
        name: tbc-ontap-nas-01
      spec:
        version: 1
        storageDriverName: ontap-nas
        managementLIF: xx.xx.xx.xx
        dataLIF: xx.xx.xx.xx
        backendName: tbc-ontap-nas-01
        svm: xxxxxxxxxxx
        credentials:
          name: tbc-ontap-nas-01-secret

- name: create trident-csi storage class 
  k8s:
    host: "https://api.{{ cluster_address }}:6443"
    validate_certs: no
    state: "{{ state }}"
    definition: 
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    allowVolumeExpansion: true
    metadata:
      name: trident-csi
    provisioner: csi.trident.netapp.io
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    parameters:
      backendType: "ontap-nas"
      provisioningType: "thin"
      snapshots: "true"
      sotragePools: "xxxxx"

