---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: "{{ USER_NAMESPACE }}"

resources:
  - ../../base

patches:
  - target:
      kind: ServiceAccount
      name: "{{ SA_NAME }}"
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: "{{ USER_NAMESPACE }}"
      - op: replace
        path: /metadata/annotations/eks.amazonaws.com~1role-arn
        value: "{{ $ESO_ROLE_ARN }}"

  - target:
      kind: SecretStore
      name: splunk-store
    patch: |-
      - op: replace
        path: /spec/provider/aws/region
        value: "{{ REGION }}"

  - target:
      kind: ExternalSecret
      name: "{{ EXTERNAL_SECRET_NAME }}"
    patch: |-
      - op: replace
        path: /spec/secretStoreRef/name
        value: "{{ SECRET_STORE_NAME }}"
      - op: replace
        path: /spec/target/name
        value: "{{ ESO_SECRET_BUCKET }}"
      - op: replace
        path: /spec/data/0/secretKey
        value: "{{ KEY1 }}"
      - op: replace
        path: /spec/data/0/remoteRef/property
        value: "{{ KEY1 }}"
      - op: replace
        path: /spec/data/0/remoteRef/key
        value: "{{ ESO_SECRET_BUCKET }}"
      - op: replace
        path: /spec/data/1/secretKey
        value: "{{ KEY2 }}"
      - op: replace
        path: /spec/data/1/remoteRef/property
        value: "{{ KEY2 }}"
      - op: replace
        path: /spec/data/1/remoteRef/key
        value: "{{ ESO_SECRET_BUCKET }}"
