---
- include_role:
    name: admin_get_service_account_token
  vars:
    admin_user: "{{ managed_admin_user }}"
    admin_password: "{{ managed_admin_password }}"
    cluster_address: "{{ managed_cluster_address }}"
    service_account_name: "{{ cluster_admin_service_account_name }}"
    service_account_namespace: "{{ cluster_admin_service_account_namespace }}"

- name: Set Managed Cluster token var
  set_fact:
    managed_cluster_token: "{{ sa_token }}"

- include_role:
    name: admin_oc_logout

- include_role:
    name: admin_get_service_account_token
  vars:
    admin_user: "{{ hub_admin_user }}"
    admin_password: "{{ hub_admin_password }}"
    cluster_address: "{{ hub_address }}"
    service_account_name: "{{ acm_service_account_name }}"
    service_account_namespace: "{{ acm_service_account_namespace }}"

- name: Set ACM Hub token var
  set_fact:
    hub_cluster_token: "{{ sa_token }}"

- name: Create namespace for managed cluster
  kubernetes.core.k8s:
    host: "https://api.{{ hub_address }}:443"
    api_key: "{{ hub_cluster_token }}"
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ managed_cluster_name }}"

- name: Create ManagedCluster custom resource
  kubernetes.core.k8s:
    host: "https://api.{{ hub_address }}:443"
    api_key: "{{ hub_cluster_token }}"
    state: "{{ state }}"
    definition:
      apiVersion: cluster.open-cluster-management.io/v1
      kind: ManagedCluster
      metadata:
        name: "{{ managed_cluster_name }}"
        labels:
          cluster.open-cluster-management.io/clusterset: "{{ cluster_set }}"
          cloud: auto-detect
          vendor: auto-detect
      spec:
        hubAcceptsClient: true

- name: Create Auto Import Secret
  kubernetes.core.k8s:
    host: "https://api.{{ hub_address }}:443"
    api_key: "{{ hub_cluster_token }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: auto-import-secret
        namespace: "{{ managed_cluster_name }}"
      stringData:
        autoImportRetry: "5"
        token: "{{ managed_cluster_token }}"
        server: "https://api.{{ managed_cluster_address }}:443"
      type: Opaque

- name: Create KlusterletAddonConfig custom resource
  kubernetes.core.k8s:
    host: "https://api.{{ hub_address }}:443"
    api_key: "{{ hub_cluster_token }}"
    definition:
      apiVersion: agent.open-cluster-management.io/v1
      kind: KlusterletAddonConfig
      metadata:
        name: "{{ managed_cluster_name }}"
        namespace: "{{ managed_cluster_name }}"
      spec:
        applicationManager:
          enabled: true
        certPolicyController:
          enabled: true
        iamPolicyController:
          enabled: true
        policyController:
          enabled: true
        searchCollector:
          enabled: true

- name: Wait for ManagedCluster to become available
  kubernetes.core.k8s_info:
    host: "https://api.{{ hub_address }}:443"
    api_key: "{{ hub_cluster_token }}"
    kind: ManagedCluster
    name: "{{ managed_cluster_name }}"
    wait: true
    wait_condition:
      reason: ManagedClusterAvailable
      type: ManagedClusterConditionAvailable
    wait_sleep: 1
...