apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: trident
  name: trident-secret
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"external-secrets.io/v1beta1","kind":"ExternalSecret","metadata":{"annotations":{},"name":"trident-secret","namespace":"trident"},"spec":{"data":[{"remoteRef":{"key":"osrosa-trident","property":"username"},"secretKey":"username"},{"remoteRef":{"key":"osrosa-trident","property":"password"},"secretKey":"password"}],"refreshInterval":"1m","secretStoreRef":{"kind":"SecretStore","name":"trident-store"},"target":{"name":"osrosa-trident"}}}
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: osrosa-trident  ##The secret name in ocp that is stored in AWS Secret Manager
        metadataPolicy: None
        property: username  ##KEY1
      secretKey: username   ##KEY1
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: osrosa-trident   ##The secret name in ocp that is stored in AWS Secret Manager
        metadataPolicy: None
        property: password  ##KEY2
      secretKey: password  #KEY2
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: trident-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: osrosa-trident   ##The secret name in ocp that is stored in AWS Secret Manager
---
