---
- name: Create IAM Role with Trust Policy and Attached Policy

  hosts: localhost
  gather_facts: no
  become: no

  vars:
    aws_iam_role_name: aws-secretmanager-clusterSB0X-service-role
    aws_iam_policy_name: aws-secretmanager-clusterSB0X-rosa-policy
    aws_iam_trust_policy_path: file/aws_iam_trustpolicy.json
    aws_iam_policy_path: file/aws_iam_policy.json
    aws_iam_policy_arn: arn:aws:iam::426428682527:policy/aws-secretmanager-clusterSB0X-rosa-policy

  tasks:
    - name: Create IAM Role
      amazon.aws.iam_role:
        name: "{{ aws_iam_role_name }}"
        assume_role_policy_document: "{{ lookup('file', aws_iam_trust_policy_path) }}"
        managed_policies:
          - arn:aws:iam::426428682527:policy/aws-secretmanager-clusterSB0X-rosa-policy ##use the content of file/aws_iam_policy.json to create the policy first with the following name: aws-secretmanager-clusterSB0X-rosa-policy 
      ##TODO: attach permissions boundary to IAM role via ansible if possible  
        #create_instance_profile: no
#       #boundary:
#          #- arn:aws:iam::426428682527:policy/Iam-role-permissions-boundary-rosa  ##attach permissions boudary to role   
