---
    - name: Create IAM Role to access ESO secrets
      amazon.aws.iam_role:
        name: "{{ aws_iam_role_name }}"
        assume_role_policy_document: "{{ lookup('template', 'aws_iam_trustpolicy.json.j2') }}"
        managed_policies:
          - "{{ aws_iam_policy_arn }}"  ##attach policy to role
        create_instance_profile: false
        boundary: "{{ aws_iam_permissions_boundary }}"  ##attach permissions boudary to role

    - name: Create IAM Role to access S3 for Observability
      amazon.aws.iam_role:
        name: "{{ aws_s3_role_name }}"
        assume_role_policy_document: "{{ lookup('template', 'aws_s3_trustpolicy.json.j2') }}"
        managed_policies:
          - "{{ aws_s3_policy_arn }}"  ##attach policy to role
        create_instance_profile: false
        boundary: "{{ aws_iam_permissions_boundary }}"  ##attach permissions boudary to role
      
    
