apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: tbc-ontap-nas-01
  namespace: trident
spec:
  version: 1
  storageDriverName: ontap-nas
  backendName: tbc-ontap-nas-01
  managementLIF: '{{ print "{{hub fromSecret "acm-install-policies" "trident-fsx-config" "management-lif" hub}}" | base64dec }}'
  dataLIF: '{{ print "{{hub fromSecret "acm-install-policies" "trident-fsx-config" "data-lif" hub}}" | base64dec }}'
  svm: '{{ print "{{hub fromSecret "acm-install-policies" "trident-fsx-config" "svm" hub}}" | base64dec }}'
  credentials:
    name: osrosa-trident
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
allowVolumeExpansion: true
metadata:
  name: trident-csi
provisioner: csi.trident.netapp.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  backendType: "ontap-nas"
  provisioningType: "thin"
  snapshots: "true"
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: trident-snapshotclass
  labels:
    velero.io/csi-volumesnapshot-class: "true"
driver: csi.trident.netapp.io
deletionPolicy: Retain
---
