apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: tbc-ontap-nas-01
  namespace: trident
spec:
  version: 1
  storageDriverName: ontap-nas
  managementLIF: zose01f0301.mmm.com
  dataLIF: zose01f0301.mmm.com
  backendName: tbc-ontap-nas-01
  svm: zose01f0301
  credentials:
    name: osrosa-trident
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
allowVolumeExpansion: true
metadata:
  name: trident-csi
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
provisioner: csi.trident.netapp.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  backendType: "ontap-nas"
  provisioningType: "thin"
  snapshots: "true"
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: trident-snapshotclass
  labels:
    velero.io/csi-volumesnapshot-class: "true"
driver: csi.trident.netapp.io
deletionPolicy: Retain
---
