#TODO This needs to be populated by the external secrets operator
#apiVersion: v1
#kind: Secret
#metadata:
#  name: tbc-ontap-nas-01-secret
#type: Opaque
#stringData:
#  username: vsadmin
#  password: xxxxxxxxxxxxxxx
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: tbc-ontap-nas-01
spec:
  version: 1
  storageDriverName: ontap-nas
  managementLIF: 10.117.28.195
  dataLIF: 10.117.28.195
  backendName: tbc-ontap-nas-01
  svm: zose01f0101
  credentials:
    name: tbc-ontap-nas-01-secret
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
allowVolumeExpansion: true
metadata:
  name: trident-csi
provisioner: csi.trident.netapp.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  backendType: "ontap-nas"
  provisioningType: "thin"
  snapshots: "true"
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: trident-snapshotclass
  labels:
    velero.io/csi-volumesnapshot-class: "true"
driver: csi.trident.netapp.io
deletionPolicy: Retain
---