---
# - name: Grant User Cluster-Admin
#  command:
#    argv:
#      - rosa
#      - grant
#      - user 
#      - cluster-admin
#      - --user 
#      - "{{ user }}"
#      - --cluster
#     - "{{ cluster }}"
#  register: cluster_admin

# - debug:
#    msg: "{{cluster_admin.stdout}}"


