apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: rhdh-operator
  name: rhdh-k8s-plugin-external-secret
  annotations:
    kubernetes.io/service-account.name: rhdh-k8s-plugin
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: osrosa-rhdh-k8s-plugin-secret  ##The secret name in ocp that is stored in AWS Secret Manager
        metadataPolicy: None
        property: ca.crt  ##KEY1
      secretKey: ca.crt   ##KEY1
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: osrosa-rhdh-k8s-plugin-secret   ##The secret name in ocp that is stored in AWS Secret Manager
        metadataPolicy: None
        property: namespace  ##KEY2
      secretKey: namespace  #KEY2
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: osrosa-rhdh-k8s-plugin-secret   ##The secret name in ocp that is stored in AWS Secret Manager
        metadataPolicy: None
        property: service-ca.crt  ##KEY3
      secretKey: service-ca.crt  #KEY3
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: osrosa-rhdh-k8s-plugin-secret   ##The secret name in ocp that is stored in AWS Secret Manager
        metadataPolicy: None
        property: token  ##KEY4
      secretKey: token  #KEY4  
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: rhdh-k8s-plugin-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: osrosa-rhdh-k8s-plugin-secret   ##The secret name in ocp that is stored in AWS Secret Manager
---