apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: rhdh-operator
  name: rhdh-external-secret
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: osrosa-rhdh-secret  ##The secret name in ocp that is stored in AWS Secret Manager
        metadataPolicy: None
        property: ARGOCD_AUTH_TOKEN  ##KEY1
      secretKey: ARGOCD_AUTH_TOKEN   ##KEY1
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: osrosa-rhdh-secret   ##The secret name in ocp that is stored in AWS Secret Manager
        metadataPolicy: None
        property: ARGOCD_INSTANCE_URL  ##KEY2
      secretKey: ARGOCD_INSTANCE_URL  #KEY2
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: osrosa-rhdh-secret   ##The secret name in ocp that is stored in AWS Secret Manager
        metadataPolicy: None
        property: ARGOCD_PASSWORD  ##KEY3
      secretKey: ARGOCD_PASSWORD  #KEY3
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: osrosa-rhdh-secret   ##The secret name in ocp that is stored in AWS Secret Manager
        metadataPolicy: None
        property: ARGOCD_USERNAME  ##KEY4
      secretKey: ARGOCD_USERNAME  #KEY4  
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: osrosa-rhdh-secret   ##The secret name in ocp that is stored in AWS Secret Manager
        metadataPolicy: None
        property: AUTH_GITHUB_APP_ID  ##KEY5
      secretKey: AUTH_GITHUB_APP_ID  #KEY5  
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: osrosa-rhdh-secret   ##The secret name in ocp that is stored in AWS Secret Manager
        metadataPolicy: None
        property: AUTH_GITHUB_CLIENT_ID  ##KEY6
      secretKey: AUTH_GITHUB_CLIENT_ID  #KEY6
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: osrosa-rhdh-secret   ##The secret name in ocp that is stored in AWS Secret Manager
        metadataPolicy: None
        property: AUTH_GITHUB_CLIENT_SECRET  ##KEY7
      secretKey: AUTH_GITHUB_CLIENT_SECRET  #KEY7 
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: osrosa-rhdh-secret   ##The secret name in ocp that is stored in AWS Secret Manager
        metadataPolicy: None
        property: GITHUB_CLIENT_SECRET  ##KEY8
      secretKey: GITHUB_CLIENT_SECRET #KEY8  
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: osrosa-rhdh-secret   ##The secret name in ocp that is stored in AWS Secret Manager
        metadataPolicy: None
        property: GITHUB_HOST_DOMAIN  ##KEY9
      secretKey: GITHUB_HOST_DOMAIN  #KEY9
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: osrosa-rhdh-secret   ##The secret name in ocp that is stored in AWS Secret Manager
        metadataPolicy: None
        property: GITHUB_ORGANIZATION  ##KEY10
      secretKey: GITHUB_ORGANIZATION #KEY10      
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: osrosa-rhdh-secret   ##The secret name in ocp that is stored in AWS Secret Manager
        metadataPolicy: None
        property: GITHUB_PRIVATE_KEY_FILE  ##KEY11
      secretKey: GITHUB_PRIVATE_KEY_FILE  #KEY11 
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: osrosa-rhdh-secret   ##The secret name in ocp that is stored in AWS Secret Manager
        metadataPolicy: None
        property: GITHUB_WEBHOOK_SECRET  ##KEY12
      secretKey: GITHUB_WEBHOOK_SECRET #KEY12
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: osrosa-rhdh-secret   ##The secret name in ocp that is stored in AWS Secret Manager
        metadataPolicy: None
        property: GITHUB_WEBHOOK_URL  ##KEY13
      secretKey: GITHUB_WEBHOOK_URL  #KEY13
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: osrosa-rhdh-secret   ##The secret name in ocp that is stored in AWS Secret Manager
        metadataPolicy: None
        property: K8S_CLUSTER_NAME  ##KEY14
      secretKey: K8S_CLUSTER_NAME #KEY14
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: osrosa-rhdh-secret   ##The secret name in ocp that is stored in AWS Secret Manager
        metadataPolicy: None
        property: K8S_CLUSTER_TOKEN  ##KEY15
      secretKey: K8S_CLUSTER_TOKEN  #KEY15 
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: osrosa-rhdh-secret   ##The secret name in ocp that is stored in AWS Secret Manager
        metadataPolicy: None
        property: K8S_CLUSTER_URL  ##KEY16
      secretKey: K8S_CLUSTER_URL #KEY16
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: osrosa-rhdh-secret   ##The secret name in ocp that is stored in AWS Secret Manager
        metadataPolicy: None
        property: QUAY_BEARER_TOKEN  ##KEY17
      secretKey: QUAY_BEARER_TOKEN  #KEY17
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: osrosa-rhdh-secret   ##The secret name in ocp that is stored in AWS Secret Manager
        metadataPolicy: None
        property: QUAY_URL  ##KEY18
      secretKey: QUAY_URL #KEY18       

  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: rhdh-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: osrosa-rhdh-secret   ##The secret name in ocp that is stored in AWS Secret Manager
---   