---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
  name: rhdh-operator
---

apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: rhdh-operator
  namespace: rhdh-operator
  annotations:
    olm.providedAPIs: Backstage.v1alpha1.rhdh.redhat.com,Backstage.v1alpha2.rhdh.redhat.com,Backstage.v1alpha3.rhdh.redhat.com
spec:
  upgradeStrategy: Default
---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhdh
  namespace: rhdh-operator
  labels:
    operators.coreos.com/rhdh.rhdh-operator: ""
spec:
  channel: fast
  installPlanApproval: Automatic
  name: rhdh
  source: redhat-operators
  sourceNamespace: openshift-marketplace 
  startingCSV: rhdh-operator.v1.4.0    


      