# ---
# - name: Configure OpenShift Logging CR
#   k8s:
#     host: "https://api.{{ cluster_address }}:6443"
#     validate_certs: no
#     state: "{{ state }}"
#     definition:
#       apiVersion: v1
#       kind: ClusterLogging
#       metadata:
#         name: instance 
#         namespace: openshift-logging 
#       spec:
#         collection:
#           type: vector
#           vector: {}
#         managementState: Managed


# # Convert token to base64 encoding by using the following command: "echo xxxxxxxxxxxxxx | base64"
# - name: Configure OpenShift Vector -> Splunk Reciver Secret from Base64 Encoded HEC Token
#   k8s:
#     host: "https://api.{{ cluster_address }}:6443"
#     validate_certs: no
#     state: "{{ state }}"
#     definition:
#       kind: Secret
#       apiVersion: v1
#       metadata:
#         name: vector-splunk-secret
#         namespace: openshift-logging
#       data:
#         hecToken: "{{ hec_token }}"
#       type: Opaque

# # - name: Configure OpenShift Log-Fowarding Service Account Permissions ~ Infrastructure
# - name: add collect-application-logs Rolebinding to the default ServiceAccount
#   k8s:
#     host: "https://api.{{ cluster_address }}:443"
#     state: "{{ state }}"
#     definition:
#       kind: ClusterRoleBinding
#       apiVersion: rbac.authorization.k8s.io/v1
#       metadata:
#         name: collect-app-logs
#       subjects:
#       - kind: ServiceAccount
#         name: default
#         namespace: openshift-logging
#       roleRef:
#          apiGroup: rbac.authorization.k8s.io
#          kind: ClusterRole
#          name: collect-application-logs
  

# # - name: Configure OpenShift Log-Fowarding Service Account Permissions ~ Application

# - name: add Log-Forwarding Rolebinding to the default ServiceAccount
#   k8s:
#     host: "https://api.{{ cluster_address }}:443"
#     state: "{{ state }}"
#     definition:
#       kind: ClusterRoleBinding
#       apiVersion: rbac.authorization.k8s.io/v1
#       metadata:
#         name: collect-infra-logs
#         subjects:
#         - kind: ServiceAccount
#           name: default
#           namespace: openshift-logging
#         roleRef:
#           apiGroup: rbac.authorization.k8s.io
#           kind: ClusterRole
#           name: collect-infrastructure-logs 
  
# - name: Configure OpenShift Log-Fowarding CR
#   k8s:
#     host: "https://api.{{ cluster_address }}:6443"
#     validate_certs: no
#     state: "{{ state }}"
#     definition:
#       apiVersion: logging.openshift.io/v1
#       kind: ClusterLogForwarder
#       metadata:
#         name: instance 
#         namespace: openshift-logging
#       spec:
#         serviceAccountName: cluster-logging-operator 
#         outputs:
#           - name: splunk-receiver 
#             secret:
#               name: vector-splunk-secret 
#             type: splunk 
#             url: "{{ hec_url }}"
#         pipelines: 
#           - inputRefs:
#               - application
#               - infrastructure
#             name: 
#             outputRefs:
#               - splunk-receiver