---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: "quarkus-example-scaled-object"
  namespace: "quarkus-pipeline"
spec:
  cooldownPeriod: 0
  maxReplicaCount: 100
  minReplicaCount: 0
  scaleTargetRef:
    name: "quarkus-example"
  triggers:
    - metadata:
        desiredReplicas: "25"
        start: "45 8 * * *"
        end: "0 10 * * *"
        timezone: "US/Mountain"
      type: cron