---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: "quarkus-example-2-scaled-object"
  namespace: "quarkus-pipeline"
spec:
  cooldownPeriod: 0
  maxReplicaCount: 15
  minReplicaCount: 0
  scaleTargetRef:
    name: "quarkus-example-2"
  triggers:
    - metadata:
        desiredReplicas: "7"
        start: "40 10 * * *"
        end: "0 12 * * *"
        timezone: "US/Mountain"
      type: cron