---
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: observability-secret
spec:
  remediationAction: enforce
  severity: high
  object-templates-raw: |
    {{/* ##  read the observability secret data ## */}}
    {{- $observabilitySecret := (lookup "v1" "Secret" "acm-install-policies" "observability-iam-config") }}
    - complianceType: musthave
      objectDefinition:
        apiVersion: observability.open-cluster-management.io/v1beta2
        kind: MultiClusterObservability
        metadata:
          name: observability
          namespace: open-cluster-management-observability
        spec:
          advanced:
            compact:
              serviceAccountAnnotations:
                eks.amazonaws.com/role-arn: arn:aws:iam::{{ $observabilitySecret.data.aws_account_id | base64dec }}:role/{{ $observabilitySecret.data.aws_s3_role_name | base64dec }}
            store:
              serviceAccountAnnotations:
                eks.amazonaws.com/role-arn: arn:aws:iam::{{ $observabilitySecret.data.aws_account_id | base64dec }}:role/{{ $observabilitySecret.data.aws_s3_role_name | base64dec }}
            rule:
              serviceAccountAnnotations:
                eks.amazonaws.com/role-arn: arn:aws:iam::{{ $observabilitySecret.data.aws_account_id | base64dec }}:role/{{ $observabilitySecret.data.aws_s3_role_name | base64dec }}
            receive:
              serviceAccountAnnotations:
                eks.amazonaws.com/role-arn: arn:aws:iam::{{ $observabilitySecret.data.aws_account_id | base64dec }}:role/{{ $observabilitySecret.data.aws_s3_role_name | base64dec }}
            query:
              serviceAccountAnnotations:
                eks.amazonaws.com/role-arn: arn:aws:iam::{{ $observabilitySecret.data.aws_account_id | base64dec }}:role/{{ $observabilitySecret.data.aws_s3_role_name | base64dec }}
          enableDownsampling: true
          observabilityAddonSpec:
            enableMetrics: true
            interval: 300
          storageConfig:
            alertmanagerStorageSize: 1Gi
            compactStorageSize: 100Gi
            metricObjectStorage:
              key: thanos.yaml
              name: thanos-object-storage
            receiveStorageSize: 100Gi
            ruleStorageSize: 1Gi
            storageClass: trident-csi
            storeStorageSize: 10Gi
