---
# apiVersion: observability.open-cluster-management.io/v1beta2
# kind: MultiClusterObservability
# metadata:
#   name: observability
# spec:
#   observabilityAddonSpec: {}
#   storageConfig:
#     metricObjectStorage:
#       name: thanos-object-storage
#       key: thanos.yaml
#       tlsSecretName: noobaa-cert
#       tlsSecretMountPath: /etc/minio/certs
      

apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  name: observability
  namespace: open-cluster-management-observability
spec:
  advanced:
    compact:
       serviceAccountAnnotations:
           eks.amazonaws.com/role-arn: arn:aws:iam::157344841078:role/eso-role
    store:
       serviceAccountAnnotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::157344841078:role/eso-role
    rule:
       serviceAccountAnnotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::157344841078:role/eso-role
    receive:
       serviceAccountAnnotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::157344841078:role/eso-role
    query:
       serviceAccountAnnotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::157344841078:role/eso-role
  enableDownsampling: true
  observabilityAddonSpec:
    enableMetrics: true
    interval: 300
  storageConfig:
    alertmanagerStorageSize: 1Gi
    compactStorageSize: 100Gi
    metricObjectStorage:
      key: thanos.yaml
      name: thanos-object-storage
    receiveStorageSize: 100Gi
    ruleStorageSize: 1Gi
    storageClass: gp3-csi
    storeStorageSize: 10Gi