---
# apiVersion: observability.open-cluster-management.io/v1beta2
# kind: MultiClusterObservability
# metadata:
#   name: observability
# spec:
#   observabilityAddonSpec: {}
#   storageConfig:
#     metricObjectStorage:
#       name: thanos-object-storage
#       key: thanos.yaml
#       tlsSecretName: noobaa-cert
#       tlsSecretMountPath: /etc/minio/certs
<<<<<<< HEAD
      
=======

###Adding observanility.yaml from CSA 
>>>>>>> b1eccce88e1f5541edd9f3333946c830e2d1aa44

apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  name: observability
  namespace: open-cluster-management-observability
spec:
  advanced:
    compact:
       serviceAccountAnnotations:
<<<<<<< HEAD
           eks.amazonaws.com/role-arn: arn:aws:iam::157344841078:role/eso-role
    store:
       serviceAccountAnnotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::157344841078:role/eso-role
    rule:
       serviceAccountAnnotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::157344841078:role/eso-role
    receive:
       serviceAccountAnnotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::157344841078:role/eso-role
    query:
       serviceAccountAnnotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::157344841078:role/eso-role
=======
           eks.amazonaws.com/role-arn: arn:aws:iam::017103373694:role/ManagedOpenShift-HCP-access-to-aws-s3-service-role
    store:
       serviceAccountAnnotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::017103373694:role/ManagedOpenShift-HCP-access-to-aws-s3-service-role
    rule:
       serviceAccountAnnotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::017103373694:role/ManagedOpenShift-HCP-access-to-aws-s3-service-role
    receive:
       serviceAccountAnnotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::017103373694:role/ManagedOpenShift-HCP-access-to-aws-s3-service-role
    query:
       serviceAccountAnnotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::017103373694:role/ManagedOpenShift-HCP-access-to-aws-s3-service-role
>>>>>>> b1eccce88e1f5541edd9f3333946c830e2d1aa44
  enableDownsampling: true
  observabilityAddonSpec:
    enableMetrics: true
    interval: 300
  storageConfig:
    alertmanagerStorageSize: 1Gi
    compactStorageSize: 100Gi
    metricObjectStorage:
      key: thanos.yaml
      name: thanos-object-storage
    receiveStorageSize: 100Gi
    ruleStorageSize: 1Gi
<<<<<<< HEAD
    storageClass: gp3-csi
    storeStorageSize: 10Gi
=======
    storageClass: trident-csi
    storeStorageSize: 10Gi
>>>>>>> b1eccce88e1f5541edd9f3333946c830e2d1aa44
