apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: open-cluster-management-observability
  name: thanos-object-storage-secret
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"external-secrets.io/v1beta1","kind":"ExternalSecret","metadata":{"annotations":{},"name":"thanos-object-storage-secret","namespace":"open-cluster-management-observability"},"spec":{"data":[{"remoteRef":{"key":"osrosa-mco-bucketname","property":"hcprosasb03-observability"},"secretKey":"hcprosasb03-observability"}],"refreshInterval":"1m","secretStoreRef":{"kind":"SecretStore","name":"observability-secret-store"},"target":{"name":"osrosa-mco-bucketname"}}}
spec:
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: osrosa-mco-bucketname
    template:
      type: generic
      data:
        thanos.yaml: |
          type: s3
          config:
            bucket: {{  .hcprosasb03-observability }} 
            endpoint: s3.us-east-1.amazonaws.com
            insecure: true
            signature_version2: false 
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: osrosa-mco-bucketname  ##The secret name in ocp that is stored in AWS Secret Manager
        metadataPolicy: None
        property: hcprosasb03-observability  ##KEY1
      secretKey: hcprosasb03-observability  ##KEY1
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
