apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: open-cluster-management-observability
  name: thanos-external-secret
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: Base64
        key: thanos-object-storage  ##The secret name in ocp that is stored in AWS Secret Manager
        property: thanos.yaml  ##KEY1
      secretKey: thanos_yaml  ##KEY1
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: thanos-secret-store
  target:
    template:
      type: generic
      data:
        thanos.yaml: "{{ `{{ .thanos_yaml }}` }}"
    creationPolicy: Owner
    deletionPolicy: Retain
    name: thanos-object-storage   ##The secret name in ocp that is stored in AWS Secret Manager
---
