apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: thanos-secret
spec:
  remediationAction: enforce
  severity: high
  object-templates-raw: |
    {{/* ##  read the bucket and endpoint access data ## */}}
    {{- $bucketSecret := (lookup "v1" "Secret" "open-cluster-management-observability" "thanos-object-storage-secret") }}
    {{/* ##  create the thanos config file as a template ## */}}
    {{- $thanosConfig := `
    type: s3
    config:
      bucket: %[1]s
      endpoint: %[2]s
      insecure: true
      signature_version2: false`
    }}

    {{/* ##  create the secret using the thanos configuration template created above. ## */}}
    - complianceType: mustonlyhave
      recreateOption: Always
      objectDefinition:
        apiVersion: v1
        kind: Secret
        metadata:
          name: thanos-object-storage
          namespace: open-cluster-management-observability
        type: Opaque
        data:
          thanos.yaml: {{ (printf $thanosConfig $bucketSecret.spec.bucketName 
                                                $bucketSecret.spec.endpoint
                          ) | base64enc }}