---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: gen-policy-generator-eso
policyDefaults:
  namespace: acm-install-policies
  remediationAction: enforce
  consolidateManifests: false
  policySets:
    - eso-install
placementBindingDefaults:
  name: "eso-binding"

policies:
  # Logging Policies - start
  - name: policy-install-eso
    manifests:
      - path: config/policy-install-eso.yaml
  # Logging Policies - end
policySets:
  - name: eso
    placement:
      placementRulePath: placements/all-placement.yaml