---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: gen-policy-generator-eso
policyDefaults:
  namespace: acm-install-policies
  remediationAction: enforce
  consolidateManifests: false
  policySets:
    - cluster-logging-operator
placementBindingDefaults:
  name: "cluster-logging-operator"

policies:
  # Logging Policies - start
  - name: policy-install-external-secrets-operator.yaml
    manifests:
      - path: config/policy-install-external-secrets-operator.yaml
  # Logging Policies - end
policySets:
  - name: cluster-logging
    placement:
      placementRulePath: placements/all-placement.yaml