apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: group-sync-operator
  name: groupsync-secret
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"external-secrets.io/v1beta1","kind":"ExternalSecret","metadata":{"annotations":{},"name":"groupsync-secret","namespace":"group-sync-operator"},"spec":{"data":[{"remoteRef":{"key":"osrosa-ldapbinding","property":"username"},"secretKey":"username"},{"remoteRef":{"key":"osrosa-ldapbinding","property":"password"},"secretKey":"password"}],"refreshInterval":"1m","secretStoreRef":{"kind":"SecretStore","name":"groupsync-store"},"target":{"name":"osrosa-ldapbinding"}}}
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: osrosa-ldapbinding  ##The secret name in ocp that is stored in AWS Secret Manager
        metadataPolicy: None
        property: username  ##KEY1
      secretKey: username   ##KEY1
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: osrosa-ldapbinding   ##The secret name in ocp that is stored in AWS Secret Manager
        metadataPolicy: None
        property: password  ##KEY2
      secretKey: password  #KEY2
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: groupsync-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: osrosa-ldapbinding   ##The secret name in ocp that is stored in AWS Secret Manager
---
