apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: group-sync-operator
  name: 3mcacerts-secret
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"external-secrets.io/v1beta1","kind":"ExternalSecret","metadata":{"annotations":{},"name":"3mcacerts-secret","namespace":"group-sync-operator"},"spec":{"data":[{"remoteRef":{"key":"osrosa-3mcacerts","property":"ca.crt"},"secretKey":"ca.crt"}],"refreshInterval":"1m","secretStoreRef":{"kind":"SecretStore","name":"3mcacerts-store"},"target":{"name":"osrosa-3mcacerts"}}}
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: osrosa-3mcacerts  ##The secret name in ocp that is stored in AWS Secret Manager
        metadataPolicy: None
        property: ca.crt  ##KEY1
      secretKey: ca.crt   ##KEY1
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: 3mcacerts-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: osrosa-3mcacerts   ##The secret name in ocp that is stored in AWS Secret Manager
---
