apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: group-sync-operator
  name: 3mcacerts-secret
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: osrosa-3mcacerts  ##The secret name in ocp that is stored in AWS Secret Manager
        metadataPolicy: None
        property: ca.crt  ##KEY1
      secretKey: ca.crt   ##KEY1
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: 3mcacerts-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: osrosa-3mcacerts   ##The secret name in ocp that is stored in AWS Secret Manager
---
