apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: openshift-logging
  name: splunk-secret
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"external-secrets.io/v1beta1","kind":"ExternalSecret","metadata":{"annotations":{},"name":"splunk-secret","namespace":"openshift-logging"},"spec":{"data":[{"remoteRef":{"key":"osrosa-splunk","property":"hecToken"},"secretKey":"hecToken"},{"remoteRef":{"key":"osrosa-splunk","property":"splunk_hec_url"},"secretKey":"splunk_hec_url"}],"refreshInterval":"1m","secretStoreRef":{"kind":"SecretStore","name":"splunk-store"},"target":{"name":"osrosa-splunk"}}}
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: osrosa-splunk  ##The secret name in ocp that is stored in AWS Secret Manager
        metadataPolicy: None
        property: hecToken  ##KEY1
      secretKey: hecToken   ##KEY1
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: osrosa-splunk   ##The secret name in ocp that is stored in AWS Secret Manager
        metadataPolicy: None
        property: splunk_hec_url  ##KEY2
      secretKey: splunk_hec_url  #KEY2
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: splunk-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: osrosa-splunk   ##The secret name in ocp that is stored in AWS Secret Manager
---
