apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-openshift-acm-managed-clusters
  namespace: acm-install-policies
spec:
  clusterSets:
    - hcp-managed-clusters
    - acs-only-clusters