---
- include_role:
    name: admin_get_service_account_token
  vars:
    service_account_name: "{{ cluster_admin_service_account_name }}"
    service_account_namespace: "{{ cluster_admin_service_account_namespace }}"

- name: Create temporary directory for template files
  tempfile:
    state: directory
    suffix: tmp
  register: tmp_dir

- set_fact:
    working_dir: "{{ tmp_dir.path }}"

- include_vars: "{{ role_path }}/files/acm-admin-auth-targets.yaml"

- name: Populate ACM RBAC Templates
  template:
    src: "{{ role_path }}/templates/acm-managed-cluster-role-bindings.yaml.j2"
    dest: "{{ working_dir }}/acm-managed-cluster-role-bindings-{{ item.auth_target }}.yaml"
  loop: "{{ auth_target_list }}"

- name: Apply ACM RBAC Templates
  k8s:
    host: "https://api.{{ cluster_address }}:6443"
    api_key: "{{ sa_token }}"
    validate_certs: no
    src: "{{ item }}"
    api_version: v1
  with_fileglob:
    - "{{ working_dir }}/*.yaml"
...