---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-cost-management-install
policyDefaults:
  namespace: acm-install-policies
  remediationAction: enforce
  consolidateManifests: false
  policySets:
    - cost-management
placementBindingDefaults:
  name: "cost-management-binding"

policies:
  - name: policy-install-cost-management
    manifests:
      - path: config/policy-install-cost-management.yaml

  - name: policy-config-cost-management
    dependencies:
      - name: policy-install-cost-management
    manifests:
      - path: config/policy-config-cost-management.yaml

  - name: policy-cost-management-status
    dependencies:
      - name: policy-config-cost-management
    manifests:
      - path: health/policy-cost-management-status.yaml
    remediationAction: inform

policySets:
  - name: cost-management
    placement:
      placementRulePath: placements/all-placement.yaml
