---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: gen-policy-generator-logging
policyDefaults:
  namespace: acm-install-policies
  remediationAction: enforce
  consolidateManifests: false
  policySets:
    - cluster-logging
placementBindingDefaults:
  name: "logging-binding"

policies:
  # Logging Policies - start
  - name: policy-install-logging.yaml
    manifests:
      - path: config/policy-install-logging.yaml
  # Logging Policies - end

  # Log Forward policy - start
  - name: logforwarder 
    manifests:
      - path: config/policy-configure-log-forwarder.yaml
  # Log Foward policy - end    
policySets:
  - name: cluster-logging
    placement:
      placementPath: placements/all-placement.yaml