apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: gen-policy-generator-trident
policyDefaults:
  namespace: acm-install-policies
  remediationAction: enforce
  consolidateManifests: false
  policySets:
    - install-trident
placementBindingDefaults:
  name: "trident-binding"
policies:
  - name: create-trident-crd
    manifests:
      - path: config/trident-orchestrator-crd.yaml

  - name: create-trident-bundle
    dependencies:
      - name: create-trident-crd
    manifests:
      - path: config/trident-bundle.yaml

  - name: install-trident
    dependencies:
      - name: create-trident-bundle
    manifests:
      - path: config/trident-orchestrator.yaml

  - name: trident-status
    remediationAction: inform
    dependencies:
      - name: install-trident
    manifests:
      - path: health/trident-health.yaml

  - name: fsx-config
    dependencies:
      - name: trident-status
    manifests:
      - path: config/fsx-config.yaml

  - name: update-default-storage-class
    dependencies:
      - name: fsx-config
    manifests:
      - path: config/update-default-storage-class.yaml

  # ESO Store policy - start
  - name: external-secrets-operator-store
    manifests:
      - path: external-secrets-operator/store/policy-externalsecret.yaml
      - path: external-secrets-operator/store/policy-secretstore.yaml
  # ESO Store policy - end        

policySets:
  - name: install-trident
    placement:
      placementPath: placements/all-placement.yaml