- name: Create Namespace
  k8s:
    host: "https://api.{{ cluster_address }}:443"
    definition:   
      apiVersion: v1
      kind: Namespace
      metadata: 
        name: acm-install-policies

###This secret is used to authenticate OCP cluster to github via github token
- name: Configure Secret for github Token
  k8s:
    host: "https://api.{{ cluster_address }}:443"
    definition:   
      apiVersion: v1
      kind: Secret
      metadata:
        name: osrosa-acm-git-secret
        namespace: acm-install-policies
      stringData:
        accessToken: "{{ accessToken }}"  
        user: "{{ user }}"
      type: Opaque