---  
apiVersion: v1
kind: Namespace
metadata:
  annotations:
  name: keycloak
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: keycloak-
  annotations:
    olm.providedAPIs: 'Keycloak.v2alpha1.k8s.keycloak.org,KeycloakRealmImport.v2alpha1.k8s.keycloak.org'
  name: keycloak-g42cv
  namespace: keycloak
spec:
  targetNamespaces:
    - keycloak
  upgradeStrategy: Default
---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhsso-operator
  namespace: keycloak
spec:
  channel: stable
  installPlanApproval: Automatic
  name: rhsso-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
