kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: acm-hub-cluster-role
rules:
  - apiGroups: ["cluster.open-cluster-management.io"]
    resources: ["managedclustersets/join", "managedclustersets/bind"]
    resourceNames: ["hub-cluster"]
    verbs: ["create"]