---

- name: Get all endpoints with specific filters
  amazon.aws.ec2_vpc_endpoint_info:
    region: "{{ region }}"
  register: existing_endpoints

- name: Get details on specific endpoint
  amazon.aws.ec2_vpc_endpoint_info:
    region: "{{ region }}"
  register: endpoint_details

- name: Debug existing_endpoints
  debug:
    var: existing_endpoints

- name: Print VPCE ID from endpoint details
  debug:
    msg: 
      - "VPCE ID: {{ endpoint_details.vpc_endpoints.vpce_id }}"
    #  - "tags: {{ endpoint_details.vpc_endpoints.tags.key=api.openshift.com/id }}"
    
    var: ansible_facts
  when: existing_endpoints is defined and existing_endpoints.vpc_id is defined

- name: set vpc-id
  set_fact:
    vpc_id: "{{ endpoint_details.vpc_endpoints[0].vpc_id }}"
    vpce_id: "{{ endpoint_details.vpc_endpoints[0].vpc_endpoint_id }}"
  
  

- name: Configure AWS VPC Endpoint to access 3M API
  command:
    argv:
      - aws
      - ec2
      - modify-vpc-endpoint
      - --vpc-endpoint-id
      - "{{ vpce_id }}"
      - --add-security-group-ids
      - "{{ DEFAULT_3M_SG_ID }}"
