
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: local-quay
  name: quay-config-external
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: osrosa-quay-config-secret  ##The secret name in ocp that is stored in AWS Secret Manager
        metadataPolicy: None
        property: host  ##KEY1
      secretKey: host   ##KEY1
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: osrosa-quay-config-secret   ##The secret name in ocp that is stored in AWS Secret Manager
        metadataPolicy: None
        property: s3_access_key  ##KEY2
      secretKey: s3_access_key  #KEY2
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: osrosa-quay-config-secret   ##The secret name in ocp that is stored in AWS Secret Manager
        metadataPolicy: None
        property: s3_bucket  ##KEY3
      secretKey: s3_bucket  #KEY3
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: osrosa-quay-config-secret   ##The secret name in ocp that is stored in AWS Secret Manager
        metadataPolicy: None
        property: s3_region  ##KEY4
      secretKey: s3_region  #KEY4  
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: osrosa-quay-config-secret   ##The secret name in ocp that is stored in AWS Secret Manager
        metadataPolicy: None
        property: s3_secret_key  ##KEY5
      secretKey: s3_secret_key  #KEY5
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: quay-config-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: osrosa-quay-config-secret   ##The secret name in ocp that is stored in AWS Secret Manager
---
