apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/quay-bridge-operator.openshift-operators: ""
  name: quay-bridge-operator
  namespace: openshift-operators
spec:
  installPlanApproval: Automatic
  name: quay-bridge-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
kind: Secret
type: Opaque
metadata:
  name: quay-integration
  namespace: openshift-operators
apiVersion: v1
data:
  token: '{{ fromSecret "local-quay" "quay-integration" "token" }}'
---
kind: Secret
type: Opaque
metadata:
  name: quay-integration
  namespace: acm-install-policies
apiVersion: v1
data:
  token: '{{ fromSecret "local-quay" "quay-integration" "token" }}'
---
apiVersion: quay.redhat.com/v1
kind: QuayIntegration
metadata:
 name: quay
 annotations:
   argocd.argoproj.io/sync-wave: "8"
spec:
 clusterID: openshift
 credentialsSecret:
   name: quay-integration
   namespace: acm-install-policies
 insecureRegistry: false
 quayHostname: https://{{ fromConfigMap "acm-install-policies" "quay-config" "host" }}
---
apiVersion: v1
data:
  '{{ (lookup "route.openshift.io/v1" "Route" "local-quay" "registry-quay" ).spec.host }}': |
    {{ ( fromSecret "openshift-ingress-operator" "router-ca" "tls.crt" ) | base64dec | autoindent }}
kind: ConfigMap
metadata:
  name: opp-ingres-ca
  namespace: openshift-config
---
apiVersion: config.openshift.io/v1
kind: Image
metadata:
 name: cluster
spec:
  additionalTrustedCA:
    name: opp-ingres-ca
---
apiVersion: v1
data:
  registry-quay-local-quay: |
    {{ ( fromSecret "openshift-ingress-operator" "router-ca" "tls.crt" ) }}
kind: Secret
metadata:
  name: opp-ingres-ca
  namespace: acm-install-policies
type: Opaque
