---
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: quay-config
spec:
  remediationAction: enforce
  severity: high
  object-templates-raw: |
    {{/* ##  read the bucket and endpoint access data ## */}}
    {{- $quaySecret := (lookup "v1" "Secret" "local-quay" "osrosa-quay-config-secret") }}
    {{/* ##  create the quay config file as a template ## */}}
    {{- $quayConfig := `
    FEATURE_USER_INITIALIZE: true
    BROWSER_API_CALLS_XHR_ONLY: false
    SUPER_USERS:
      - quayadmin
    FEATURE_USER_CREATION: true
    FEATURE_SUPERUSERS_FULL_ACCESS: true
    DISTRIBUTED_STORAGE_CONFIG:
      s3Storage:
        - S3Storage
        - host: %[1]s
          s3_access_key: %[2]s
          s3_secret_key: %[3]s
          s3_bucket: %[4]s
          s3_region: %[5]s
          storage_path: /datastorage/registry
    DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
    DISTRIBUTED_STORAGE_PREFERENCE:
        - s3Storage`
    }}

    {{/* ##  create the secret using the quay configuration template created above. ## */}}
    - complianceType: mustonlyhave
      objectDefinition:
        apiVersion: v1
        kind: Secret
        metadata:
          name: init-config-bundle-secret
          namespace: local-quay
        type: Opaque
        data:
          config.yaml: {{ (printf $quayConfig ($quaySecret.data.host | base64dec) 
                                              ($quaySecret.data.s3_access_key | base64dec)
                                              ($quaySecret.data.s3_secret_key | base64dec)
                                              ($quaySecret.data.s3_bucket | base64dec)
                                              ($quaySecret.data.s3_region | base64dec)
                          ) | base64enc }}
