---
- include_role:
    name: admin_get_service_account_token
  vars:
    service_account_name: "{{ acm_service_account_name }}"
    service_account_namespace: "{{ acm_service_account_namespace }}"

- name: Create temporary directory for template files
  tempfile:
    state: directory
    suffix: tmp
  register: tmp_dir

- set_fact:
    working_dir: "{{ tmp_dir.path }}"

- name: Populate Templates
  template:
    src: "{{ role_path }}/templates/subscription.yaml.j2"
    dest: "{{ working_dir }}/subscription.yaml"

- name: Create App Namespace
  k8s:
    host: "https://api.{{ cluster_address }}:443"
    api_key: "{{ sa_token }}"
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ app_namespace }}"

- name: Apply eso Operator install module repo subscription
  k8s:
    host: "https://api.{{ cluster_address }}:443"
    api_key: "{{ sa_token }}"
    src: "{{ working_dir }}/subscription.yaml"
    state: "{{ state }}"

#TODO Move ARN to variables
- name: create service account
  k8s:
    host: "https://api.{{ cluster_address }}:443"
    api_key: "{{ sa_token }}"
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: splunk-logging
        ## Openshift namespace where the secret going to be created in
        namespace: openshift-logging
      annotations:
         eks.amazonaws.com/role-arn: arn:aws:iam::973284986717:role/eso-splunk  ##AWS ESO_ROLE_ARN
