---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
  name: group-sync-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: group-sync-operator
  namespace: group-sync-operator
spec:
  targetNamespaces:
    - group-sync-operator
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: group-sync-operator
  namespace: group-sync-operator
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: group-sync-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: group-sync-operator.v0.0.30
