---
- name: Install OCP Infrastructure Components
  gather_facts: false
  hosts: localhost
#  vars_prompt:
#    # Prompt for cluster name
#    - name: ocp_cluster_address
#      prompt: Enter OCP Cluster Address (e.g. clustername.domain.com)
#      private: no
#      confirm: no
#    # Prompt for cluster-admin username
#    - name: cluster_admin_user
#      prompt: Enter cluster-admin user
#      private: no
#      confirm: no
#    # Prompt for cluster-admin password
#    - name: cluster_admin_password
#      prompt: Enter cluster-admin password
#      private: yes
#      confirm: no
  tasks:
    - include_role:
        name: admin_provision_hcp_cluster

    - include_role:
        name: aws_config_security_groups

    # TODO Create Cluster Admin using rosa CLI

    - include_role:
        name: admin_config_ldap

    - include_role:
        name: install_groupsync_from_subscription
      vars:
        cluster_address: "{{ ocp_cluster_address }}"

    # TODO Create trident-csi as default StorageClass (FSXn)

    - include_role:
        name: admin_config_rbac

    - include_role:
        name: admin_config_machine-pool

#    - include_role:
#        name: admin_config_log_forwarder

    - include_role:
        name: admin_oc_logout
...