---
- name: Provision OCP HCP Cluster on AWS
  gather_facts: false
  hosts: localhost
# Required Variables for this playbook
#    aws_account_id: xxxxxxxxx
#    account_roles_prefix: Managed-OpenShift
#    operator_roles_prefix: Managed-OpenShift-HCP
#    cluster_name: xxxxxxx
#    kms_arn: arn:aws:kms:xxxxxxxx
#    vpc_cidr: 10.0.0.0/16
#    subnet_id1: subnet-xxxxxxxxxxxxx
#    subnet_id2: subnet-xxxxxxxxxxxxx
#    subnet_id3: subnet-xxxxxxxxxxxxx
#    compute_machine_type: m5.xlarge
  tasks:
    - include_role:
        name: admin_provision_hcp_cluster

    # TODO Move this out of here, into install-infra playbook. This is only for connection provisioning to Day 2 config
    - name: Waiting for Cluster to Start (This will take several minutes...)
      command:
        argv:
          - rosa
          - logs
          - install
          - --cluster
          - "{{ cluster_name }}"
          - --watch
      register: logs_install

    - debug:
        msg: "{{ logs_install.stdout_lines }}"
