---
- name: Apply Day 2 Configuration to OCP HCP Services Cluster
  gather_facts: false
  hosts: localhost
  #  vars:
  # Required Variables for this Playbook
  #    type: "LDAP"
  #    name: "MYLDAP"
  #    cluster_name: hcp-cluster
  #    url: "ldaps://xxxxxxxxxxxx"
  #    bind_password: "xxxxxxxxx"
  #    bind_dn: "xxxxxxxxxx"
  #    id_attributes: "dn"
  #    name_attributes: "cn"
  #    email_attributes: "mail"
  #    username_attributes: "uid"
  #    region: "us-east-1"
  #    DEFAULT_XX_SG_ID: "sg-xxxxxxxxxxxxx"
  #    VpcId: "xxxxxxx"
  #    VpcEndpointId: "xxxxxxxxxx"
  tasks:
    # Ensure we're not still logged in under another account
    - include_role:
        name: admin_oc_logout

    - include_role:
        name: install_acm
      vars:
        cluster_address: "{{ ocp_cluster_address }}"
        admin_user: "{{ cluster_admin_user }}"
        admin_password: "{{ cluster_admin_password }}"

    - include_role:
        name: admin_create_acm_service_account
      vars:
        cluster_address: "{{ ocp_cluster_address }}"
        admin_user: "{{ cluster_admin_user }}"
        admin_password: "{{ cluster_admin_password }}"

    - include_role:
        name: admin_config_ldap

    - include_role:
        name: admin_config_machine_pool
      vars:
        subnet: "{{ subnet_id1 }}"
        machinepool_name: quay-1
        machinepool_labels: node-role.kubernetes.io/infra=,node-role.kubernetes.io/quay=
        machinepool_taints: ''
        min_replicas: 1
        max_replicas: 1
        instance_type: m5a.2xlarge

    - include_role:
        name: admin_config_machine_pool
      vars:
        subnet: "{{ subnet_id2 }}"
        machinepool_name: quay-2
        machinepool_labels: node-role.kubernetes.io/infra=,node-role.kubernetes.io/quay=
        machinepool_taints: ''
        min_replicas: 1
        max_replicas: 1
        instance_type: m5a.2xlarge

    - include_role:
        name: admin_config_machine_pool
      vars:
        subnet: "{{ subnet_id3 }}"
        machinepool_name: quay-3
        machinepool_labels: node-role.kubernetes.io/infra=,node-role.kubernetes.io/quay=
        machinepool_taints: ''
        min_replicas: 1
        max_replicas: 1
        instance_type: m5a.2xlarge

    - include_role:
        name: admin_config_acm_github_authentication
      vars:
        cluster_address: "{{ ocp_cluster_address }}"
        admin_user: "{{ cluster_admin_user }}"
        admin_password: "{{ cluster_admin_password }}"

    - include_role:
        name: aws_create_configmap
      vars:
        cluster_address: "{{ ocp_cluster_address }}"
        service_account_name: "{{ acm_service_account_name }}"
        service_account_namespace: "{{ acm_service_account_namespace }}"

    - include_role:
        name: install_groupsync_from_subscription
      vars:
        cluster_address: "{{ ocp_cluster_address }}"

    - include_role:
        name: install_eso_from_subscription
      vars:
        cluster_address: "{{ ocp_cluster_address }}"

    - include_role:
        name: admin_config_rbac
      vars:
        cluster_address: "{{ ocp_cluster_address }}"

    - include_role:
        name: install_trident_from_subscription
      vars:
        cluster_address: "{{ ocp_cluster_address }}"

    - include_role:
        name: install_mco_from_subscription
      vars:
        cluster_address: "{{ ocp_cluster_address }}"

    - include_role:
        name: install_logging_from_subscription
      vars:
        cluster_address: "{{ ocp_cluster_address }}"

    - include_role:
        name: install_acs_from_subscription
      vars:
        cluster_address: "{{ ocp_cluster_address }}"

    - include_role:
        name: install_quay_from_subscription
      vars:
        cluster_address: "{{ ocp_cluster_address }}"

    - include_role:
        name: install_cma_from_subscription
      vars:
        cluster_address: "{{ ocp_cluster_address }}"

    - include_role:
        name: install_cost_management_from_subscription
      vars:
        cluster_address: "{{ ocp_cluster_address }}"

    - include_role:
        name: install_openshift_pipelines_from_subscription
      vars:
        cluster_address: "{{ ocp_cluster_address }}"

    - include_role:
        name: install_developer_hub_from_subscription
      vars:
        cluster_address: "{{ ocp_cluster_address }}"

    # TODO Cleanup Automation Admin Accounts

    - include_role:
        name: admin_oc_logout