---
- include_role:
    name: admin_get_service_account_token
  vars:
    service_account_name: "{{ acm_service_account_name }}"
    service_account_namespace: "{{ acm_service_account_namespace }}"

- name: Create temporary directory for template files
  tempfile:
    state: directory
    suffix: tmp
  register: tmp_dir

- set_fact:
    working_dir: "{{ tmp_dir.path }}"

- name: Populate Templates
  template:
    src: "{{ role_path }}/templates/{{ item }}.yaml.j2"
    dest: "{{ working_dir }}/{{ item }}.yaml"
  loop:
    - subscription
    - trident-fsx-config

- name: Create App Namespace
  k8s:
    host: "https://api.{{ cluster_address }}:443"
    api_key: "{{ sa_token }}"
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ app_namespace }}"

- name: Create Trident Namespace
  k8s:
    host: "https://api.{{ cluster_address }}:443"
    api_key: "{{ sa_token }}"
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        labels:
          pod-security.kubernetes.io/enforce: privileged
        name: trident

- name: Apply Trident FSx Config Secret
  k8s:
    host: "https://api.{{ cluster_address }}:443"
    api_key: "{{ sa_token }}"
    src: "{{ working_dir }}/trident-fsx-config.yaml"
    state: "{{ state }}"

- name: Apply Trident Operator install module repo subscription
  k8s:
    host: "https://api.{{ cluster_address }}:443"
    api_key: "{{ sa_token }}"
    src: "{{ working_dir }}/subscription.yaml"
    state: "{{ state }}"

- name: create service account
  k8s:
    host: "https://api.{{ cluster_address }}:443"
    api_key: "{{ sa_token }}"
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: externalsecret-operator-config-external-secrets
        namespace: trident ##Openshift namespace where the secret going to be created in
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::{{ aws_account_id }}:role/{{ aws_iam_role_name }}  ##AWS ESO_ROLE_ARN