apiVersion: costmanagement-metrics-cfg.openshift.io/v1beta1
kind: CostManagementMetricsConfig
metadata:
  name: costmanagement-metrics-config
  namespace: costmanagement-metrics-operator
spec:
  upload:
    ingress_path: /api/ingress/v1/upload
    upload_cycle: 60
    upload_toggle: true
    validate_cert: true
  packaging:
    max_reports_to_store: 30
    max_size_MB: 100
  api_url: 'https://console.redhat.com'
  prometheus_config:
    collect_previous_data: true
    context_timeout: 120
    disable_metrics_collection_cost_management: false
    disable_metrics_collection_resource_optimization: false
    service_address: 'https://thanos-querier.openshift-monitoring.svc:9091'
    skip_tls_verification: false
  authentication:
    token_url: 'https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token'
    type: token
  source:
    check_cycle: 1440
    create_source: true
    sources_path: /api/sources/v1.0/
    name: '{{ fromSecret "open-cluster-management-agent" "hub-kubeconfig-secret" "cluster-name" | base64dec }}'
    #name: '{{ print "{{hub fromSecret "acm-install-policies" "cost-management-secret-config" "cluster_name" hub}}" | base64dec }}'